### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by hacker-h** [pilotak/docker-rpi-ws281x-mqtt#1]
I'm using a ws2812 strip on a raspberry pi 4.

Using the docker compose file provided in the readme I get the following output:
```
$ docker-compose up
Starting rpi_ws281x ... done
Attaching to rpi_ws281x
rpi_ws281x    | Setting up 10 LEDS on pin 18
rpi_ws281x    | Setup of WS281x successfull
rpi_ws281x    | Traceback (most recent call last):
rpi_ws281x    |   File "ws281x.py", line 175, in <module>
rpi_ws281x    |     mqtt.connect(MQTT_BROKER, MQTT_PORT)
rpi_ws281x    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
rpi_ws281x    |     return self.reconnect()
rpi_ws281x    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
rpi_ws281x    |     sock = self._create_socket_connection()
rpi_ws281x    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
rpi_ws281x    |     return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
rpi_ws281x    |   File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
rpi_ws281x    |     raise err
rpi_ws281x    |   File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
rpi_ws281x    |     sock.connect(sa)
rpi_ws281x    | OSError: [Errno 99] Cannot assign requested address
rpi_ws281x    | swig/python detected a memory leak of type 'ws2811_t *', no destructor found.
rpi_ws281x exited with code 1
```
However I managed to get the strip working with an approach using the Adafruit_NeoPixel object:
https://github.com/jgarff/rpi_ws281x/blob/master/python/examples/strandtest.py

Therefore the error could be related to the fact that this project actually creates a ws2811 object:
https://github.com/pilotak/docker-rpi-ws281x-mqtt/blob/master/ws281x.py#L140

Not certain whether this is compatible, did you test it yet with any other led strips?

**Comment by pilotak** [comment]
I'm running this image on PI4 too. This is not related to ws2812 library but to mqtt - the log is saying that you have a wrong mqtt address. If you run mqtt broker as a hass.io component then you need set env to PI4 address ie `MQTT_BROKER=192.168.0.5` or whatever address you have.
If you run the broker throu docker-compose then use `MQTT_BROKER=mosquitto` or other name you named you image and you should add it as dependency
```yaml
version: "3.6"
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ${DOCKER_PATH}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${DOCKER_PATH}/mosquitto/pwfile:/mosquitto/config/pwfile
      - ${DOCKER_PATH}/mosquitto/data:/mosquitto/data

  rpi_ws281x:
    container_name: rpi_ws281x
    restart: unless-stopped
    image: pilotak/rpi-ws281x-mqtt
    privileged: true
    depends_on:
      - mosquitto
    environment:
      - LED_GPIO=12
      - LED_COUNT=10
      - MQTT_BROKER=mosquitto
      - MQTT_USER=user
      - MQTT_PASSWORD=123456

```
